version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aspnet-api
    expose:
      - "80"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet

networks:
  webnet:
