version: "3.9"

services:
  api:
    build: .
    image: redasaad123/eslamoffer
    volumes:
      - ./uploads:/app/ProjectApi/uploads
    env_file:
      - .env
    environment: []
    expose:
      - "80"
    networks:
      - webnet
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - webroot:/var/www/html
    networks:
      - webnet

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
    networks:
      - webnet
    command: certonly --webroot --webroot-path=/var/www/html --email support@eslamoffer.com --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d api.eslamoffer.com

  certbot-renew:
    image: certbot/certbot
    volumes:
      - webroot:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - webnet

networks:
  webnet:

volumes:
  webroot:
  certbot-etc:
  certbot-var:

# version: "3.9"

# services:
#   api:
#     build: .
#     image: redasaad123/eslamoffer
#     volumes:
#       - ./uploads:/app/ProjectApi/uploads
#     env_file:
#       - .env
#     # environment:
#     #   - VIRTUAL_HOST=api.eslamoffers.com
#     expose:
#       - "80"
#     networks:
#       - webnet
#     deploy:
#       replicas: 3
#       restart_policy:
#         condition: on-failure
#         delay: 5s
#       update_config:
#         parallelism: 2
#         delay: 10s

#   nginx:
#     image: nginx:latest
#     container_name: nginx-proxy
#     depends_on:
#       - api
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./certs:/etc/letsencrypt:ro
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#       - webroot:/var/www/html
#       - certbot-etc:/etc/letsencrypt
#     networks:
#       - webnet

#   certbot:
#     image: certbot/certbot
#     container_name: certbot
#       - ./certs:/etc/letsencrypt
#       - webroot:/var/www/html
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
#     depends_on:
#       - nginx
#     command: certonly --webroot --webroot-path=/var/www/html --email support@eslamoffer.com --agree-tos --no-eff-email --non-interactive --keep-until-expiring -d api.eslamoffers.com

#   certbot-renew:
#     image: certbot/certbot
#     volumes:
#       - webroot:/var/www/html
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
#     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#     networks:
#       - webnet

# networks:
#   webnet:

# volumes:
#   webroot:
#   certbot-etc:
#   certbot-var:
# version: "3.9"

# services:
#   api:
#     image: redasaad123/eslamoffer
#     build: .
#     volumes:
#       - ./uploads:/app/ProjectApi/uploads
#     env_file:
#       - .env
#     expose:
#       - "80"
#     networks:
#       - webnet
#     deploy:
#       replicas: 3
#       restart_policy:
#         condition: on-failure
#         delay: 5s
#       update_config:
#         parallelism: 2
#         delay: 10s

#   nginx:
#     image: nginx:latest
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#       - webroot:/var/www/html
#       - certbot-etc:/etc/letsencrypt
#     networks:
#       - webnet
#     deploy:
#       placement:
#         constraints:
#           - node.role == manager

#   certbot:
#     image: certbot/certbot
#     volumes:
#       - webroot:/var/www/html
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
#     networks:
#       - webnet
#     command: >
#       certonly --webroot
#       --webroot-path=/var/www/html
#       --email support@eslamoffer.com
#       --agree-tos
#       --no-eff-email
#       --non-interactive
#       --keep-until-expiring
#       -d api.eslamoffers.com
#     deploy:
#       restart_policy:
#         condition: none
#       replicas: 0  # يشغلها يدوي وقت الحاجة فقط

#   certbot-renew:
#     image: certbot/certbot
#     entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
#     volumes:
#       - webroot:/var/www/html
#       - certbot-etc:/etc/letsencrypt
#       - certbot-var:/var/lib/letsencrypt
#     networks:
#       - webnet
#     deploy:
#       replicas: 1
#       restart_policy:
#         condition: on-failure

# networks:
#   webnet:
#     driver: overlay
#     attachable: true

# volumes:
#   webroot:
#   certbot-etc:
#   certbot-var:

