version: "3.9"

services:
  api:
    build: .
    image: redasaad123/eslamoffer
    volumes:
      - ./uploads:/app/ProjectApi/uploads
    env_file:
      - .env
    environment:
      - ConnectionStrings__ProdcutionConnection=${PRODUCTION_CONN}
      - ConnectionStrings__DefaultConnection=${DEFAULT_CONN}
    expose:
      - "80"
    networks:
      - webnet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
      update_config:
        parallelism: 2
        delay: 10s

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - api
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webnet

networks:
  webnet:

